---
title: "make rmd public"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, cache=T}
#escapement = read.table("clipboard", header=T, sep="\t")
escapement = read.csv("knb.92020.1.csv", stringsAsFactors = F)
```

```{r}
library(tidyr)
library(dplyr)
library(leaflet)
library(ggplot2)
library(DT)
```

```{r, echo = F}
names(escapement)
summary(escapement)
```

```{r}
median_esc = escapement %>%
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-")%>%
  group_by(Species, Location, Year) %>%
  summarize(escapement = sum(DailyCount, na.rm=T)) %>%
  group_by(Species) %>%
  summarise(median_esc = median(escapement))
```

```{r}
names(median_esc)
```

```{r}
ggplot(median_esc, aes(Species, median_esc)) +
  geom_col() +
  coord_flip()
```

```{r}
datatable(median_esc)
```

```{r}
names(escapement)

locations = escapement %>%
  distinct(Location, Latitude, Longitude) %>%
  drop_na()

#summary(locations)
leaflet(locations) %>%
  addTiles() %>%
  addMarkers(~-abs(Longitude), ~Latitude, popup = ~Location)

```
Leflet has documentation that lists more tiles 





